<#
    Tests for the agent-thread filter in Get-AzureDevOpsPR.ps1 (PR #61 review).

    Test-AgentAuthoredThread decides which existing comment threads belong to a
    previous automated review and therefore enter the COPILOT COMMENT THREADS
    JSON that the agent may resolve. A false positive here leaks human threads
    to the agent — the original -like implementation did exactly that, because
    [brackets] in a wildcard pattern form a character class rather than literal
    text. The function is extracted via the PowerShell AST for direct unit
    testing.

    Requires Pester 5+. Run via: pwsh -File tests/powershell/Invoke-Tests.ps1
#>

BeforeAll {
    $repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
    $script:PrScript = Join-Path $repoRoot 'CopilotCodeReviewV1/scripts/Get-AzureDevOpsPR.ps1'

    $tokens = $null
    $parseErrors = $null
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($PrScript, [ref]$tokens, [ref]$parseErrors)
    if ($parseErrors.Count -gt 0) {
        throw "Get-AzureDevOpsPR.ps1 failed to parse: $($parseErrors -join '; ')"
    }
    foreach ($functionName in 'Test-AgentAuthoredThread', 'Test-TrustedAgentAuthoredThread') {
        $funcAst = $ast.Find({
            param($node)
            $node -is [System.Management.Automation.Language.FunctionDefinitionAst] -and
            $node.Name -eq $functionName
        }, $true)
        if (-not $funcAst) {
            throw "$functionName function not found in Get-AzureDevOpsPR.ps1."
        }
        . ([scriptblock]::Create($funcAst.Extent.Text))
    }

    # Builds a minimal thread object shaped like the ADO threads API response
    function New-Thread {
        param(
            [string]$Content,
            [string]$DisplayName = 'Jane Reviewer',
            [string]$UniqueName = 'jane@example.com',
            [string]$Descriptor = 'aad.reviewer'
        )
        [pscustomobject]@{
            comments = @(
                [pscustomobject]@{
                    content = $Content
                    author  = [pscustomobject]@{
                        displayName = $DisplayName
                        uniqueName  = $UniqueName
                        descriptor  = $Descriptor
                    }
                }
            )
        }
    }
}

Describe 'Test-AgentAuthoredThread' {

    It 'rejects an ordinary human comment' {
        # Regression for the -like character-class bug: this text contains many
        # letters from the attribution tag but not the tag itself
        Test-AgentAuthoredThread -Thread (New-Thread -Content 'Please fix the null check here.') | Should -BeFalse
    }

    It 'rejects a human comment that mentions the agent without the bracketed tag' {
        Test-AgentAuthoredThread -Thread (New-Thread -Content 'This was Generated by GitHub Copilot, I think?') | Should -BeFalse
    }

    It 'accepts a thread authored by the Build Service identity' {
        $thread = New-Thread -Content 'Anything at all' -DisplayName 'TestProject Build Service (testorg)' -UniqueName 'build@testorg'
        Test-AgentAuthoredThread -Thread $thread | Should -BeTrue
    }

    It 'accepts a Build Service match on uniqueName alone' {
        $thread = New-Thread -Content 'Anything at all' -DisplayName 'Service Account' -UniqueName 'svc.Build Service.testorg'
        Test-AgentAuthoredThread -Thread $thread | Should -BeTrue
    }

    It 'accepts a PAT-authored comment carrying the Copilot attribution tag' {
        Test-AgentAuthoredThread -Thread (New-Thread -Content "Looks good!`n`n[Generated by GitHub Copilot]") | Should -BeTrue
    }

    It 'accepts a PAT-authored comment carrying the Claude Code attribution tag' {
        Test-AgentAuthoredThread -Thread (New-Thread -Content "Consider renaming this.`n`n[Generated by Claude Code]") | Should -BeTrue
    }
}

Describe 'Test-TrustedAgentAuthoredThread' {

    It 'accepts a Build Service thread for authenticated mutation' {
        $thread = New-Thread -Content 'Automated feedback' `
            -DisplayName 'TestProject Build Service (testorg)' -Descriptor 'svc.build-identity'
        Test-TrustedAgentAuthoredThread -Thread $thread | Should -BeTrue
    }

    It 'rejects a user identity with a spoofed Build Service display name' {
        $thread = New-Thread -Content 'Human feedback' -DisplayName 'TestProject Build Service (testorg)'
        Test-TrustedAgentAuthoredThread -Thread $thread | Should -BeFalse
    }

    It 'rejects a human thread with a spoofed Copilot attribution tag' {
        $thread = New-Thread -Content "Human feedback`n`n[Generated by GitHub Copilot]"
        Test-TrustedAgentAuthoredThread -Thread $thread | Should -BeFalse
    }

    It 'rejects a human thread with a spoofed Claude attribution tag' {
        $thread = New-Thread -Content "Human feedback`n`n[Generated by Claude Code]"
        Test-TrustedAgentAuthoredThread -Thread $thread | Should -BeFalse
    }
}
