<#
.SYNOPSIS
    Retrieves Copilot-generated comments from a pull request.

.DESCRIPTION
    This script is used by GitHub Copilot to retrieve previously generated comments
    from a pull request. It simplifies the calling process by populating the necessary
    parameters automatically from environment variables set by the pipeline task.

.PARAMETER CopilotOnly
    Optional. If specified, only returns comments that contain "[Generated by GitHub Copilot]" tag.
    Default is $true.

.EXAMPLE
    .\Get-CopilotComments.ps1
    Retrieves all Copilot-generated comments.

.EXAMPLE
    .\Get-CopilotComments.ps1 -CopilotOnly:$false
    Retrieves all comments (not just Copilot-generated ones).

.NOTES
    Author: Little Fort Software
    Date: January 2026
    Requires: PowerShell 5.1 or later
    
    Environment Variables Used:
    - AZUREDEVOPS_TOKEN: Authentication token (PAT or OAuth)
    - AZUREDEVOPS_AUTH_TYPE: 'Basic' for PAT, 'Bearer' for OAuth
    - ORGANIZATION: Azure DevOps organization name
    - PROJECT: Azure DevOps project name
    - REPOSITORY: Repository name
    - PRID: Pull request ID
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false, HelpMessage = "Filter for Copilot-generated comments only")]
    [bool]$CopilotOnly = $true
)

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

Write-Host "Retrieving $(if ($CopilotOnly) { 'Copilot-generated ' })comments from PR #${env:PRID}..." -ForegroundColor DarkGray

& "$scriptDir\Get-AzureDevOpsPR.ps1" `
    -Token ${env:AZUREDEVOPS_TOKEN} `
    -AuthType ${env:AZUREDEVOPS_AUTH_TYPE} `
    -Organization ${env:ORGANIZATION} `
    -Project ${env:PROJECT} `
    -Repository ${env:REPOSITORY} `
    -Id ${env:PRID} `
    -CopilotOnly:$CopilotOnly
